server:
  port: 8003
spring:
  application:
    name: provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
#    password: 123456

# eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka

logging:
  level:
    root: INFO
