server:
  port: 8001
spring:
  application:
    name: consumer
  redis:
    host: localhost
    port: 6379
    password: 123456

# eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka

logging:
  level:
    root: INFO

feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

hystrix:
  command:
    default:
      execution:
        timeout:
          enable: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000
